#!/bin/bash
chown -R www:www /www
chown -R mysql:mysql /data/mysql
chown -R www:www /usr/local/php5
chown -R www:www /usr/local/php7
chown -R www:www /usr/local/node
chown -R www:www /usr/local/nginx

