#!/bin/bash
if [ $1x == "5"x ]; then
    systemctl stop    php7
    systemctl disable php7
    systemctl restart php5
    systemctl enable  php5
elif [ $1x == "7"x ]; then
    systemctl stop    php5
    systemctl disable php5
    systemctl restart php7
    systemctl enable  php7
else
    echo -e 'pvm\n    5        Switch to php-5.6.40\n    7        Switch to php-7.3.24'
    echo -e 'PHP CLI Usage:\n    php5 [options] [-f] <file> [--] [args...]\n    php7 [options] [-f] <file> [--] [args...]'
fi
